export const mockAiActivity = [
    {
        id: "activity_001",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Amazing Facts Daily"',
        projectId: "project_002",
        contentId: "content_101",
        createdAt: "2026-08-12T17:28:00Z",
    },
    {
        id: "activity_002",
        type: "seo_metadata_generated",
        title: "SEO metadata generated",
        description: 'SEO suggestions ready for "Science Explained"',
        projectId: "project_003",
        contentId: "content_102",
        createdAt: "2026-08-12T17:20:00Z",
    },
    {
        id: "activity_003",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Tech in 60 Seconds"',
        projectId: "project_001",
        contentId: "content_103",
        createdAt: "2026-08-12T16:54:00Z",
    },
    {
        id: "activity_004",
        type: "thumbnail_generated",
        title: "Thumbnail generated",
        description: 'AI generated a thumbnail for "Top 10 Space Discoveries"',
        projectId: "project_004",
        contentId: "content_104",
        createdAt: "2026-08-12T16:31:00Z",
    },
    {
        id: "activity_005",
        type: "video_generated",
        title: "Video generated",
        description: 'Video successfully generated for "Daily History"',
        projectId: "project_005",
        contentId: "content_105",
        createdAt: "2026-08-12T15:48:00Z",
    },
    {
        id: "activity_006",
        type: "seo_metadata_generated",
        title: "SEO metadata generated",
        description: 'SEO suggestions ready for "World Mysteries"',
        projectId: "project_006",
        contentId: "content_106",
        createdAt: "2026-08-12T15:22:00Z",
    },
    {
        id: "activity_007",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Finance Simplified"',
        projectId: "project_007",
        contentId: "content_107",
        createdAt: "2026-08-12T14:59:00Z",
    },
    {
        id: "activity_008",
        type: "content_published",
        title: "Content published",
        description: '"Interesting Animal Facts" was published successfully',
        projectId: "project_008",
        contentId: "content_108",
        createdAt: "2026-08-12T14:36:00Z",
    },
    {
        id: "activity_009",
        type: "thumbnail_generated",
        title: "Thumbnail generated",
        description: 'AI generated a thumbnail for "Future of AI"',
        projectId: "project_009",
        contentId: "content_109",
        createdAt: "2026-08-12T14:12:00Z",
    },
    {
        id: "activity_010",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Mind Blowing Facts"',
        projectId: "project_002",
        contentId: "content_110",
        createdAt: "2026-08-12T13:47:00Z",
    },
    {
        id: "activity_011",
        type: "seo_metadata_generated",
        title: "SEO metadata generated",
        description: 'SEO suggestions ready for "Healthy Living Tips"',
        projectId: "project_010",
        contentId: "content_111",
        createdAt: "2026-08-12T13:19:00Z",
    },
    {
        id: "activity_012",
        type: "video_generated",
        title: "Video generated",
        description: 'Video successfully generated for "Ocean Wonders"',
        projectId: "project_011",
        contentId: "content_112",
        createdAt: "2026-08-12T12:55:00Z",
    },
    {
        id: "activity_013",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Quick Science"',
        projectId: "project_003",
        contentId: "content_113",
        createdAt: "2026-08-12T12:31:00Z",
    },
    {
        id: "activity_014",
        type: "content_published",
        title: "Content published",
        description: '"The History of Space Travel" was published successfully',
        projectId: "project_004",
        contentId: "content_114",
        createdAt: "2026-08-12T12:08:00Z",
    },
    {
        id: "activity_015",
        type: "thumbnail_generated",
        title: "Thumbnail generated",
        description: 'AI generated a thumbnail for "Ancient Civilizations"',
        projectId: "project_005",
        contentId: "content_115",
        createdAt: "2026-08-12T11:44:00Z",
    },
    {
        id: "activity_016",
        type: "seo_metadata_generated",
        title: "SEO metadata generated",
        description: 'SEO suggestions ready for "Coding Tips Daily"',
        projectId: "project_012",
        contentId: "content_116",
        createdAt: "2026-08-12T11:21:00Z",
    },
    {
        id: "activity_017",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "World Geography"',
        projectId: "project_013",
        contentId: "content_117",
        createdAt: "2026-08-12T10:58:00Z",
    },
    {
        id: "activity_018",
        type: "video_generated",
        title: "Video generated",
        description: 'Video successfully generated for "Amazing Inventions"',
        projectId: "project_014",
        contentId: "content_118",
        createdAt: "2026-08-12T10:32:00Z",
    },
    {
        id: "activity_019",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Psychology Explained"',
        projectId: "project_015",
        contentId: "content_119",
        createdAt: "2026-08-12T10:09:00Z",
    },
    {
        id: "activity_020",
        type: "content_published",
        title: "Content published",
        description: '"10 Facts About the Human Brain" was published successfully',
        projectId: "project_015",
        contentId: "content_120",
        createdAt: "2026-08-12T09:42:00Z",
    },
    {
        id: "activity_021",
        type: "thumbnail_generated",
        title: "Thumbnail generated",
        description: 'AI generated a thumbnail for "Hidden Places on Earth"',
        projectId: "project_016",
        contentId: "content_121",
        createdAt: "2026-08-12T09:18:00Z",
    },
    {
        id: "activity_022",
        type: "seo_metadata_generated",
        title: "SEO metadata generated",
        description: 'SEO suggestions ready for "Startup Stories"',
        projectId: "project_017",
        contentId: "content_122",
        createdAt: "2026-08-12T08:54:00Z",
    },
    {
        id: "activity_023",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Business Basics"',
        projectId: "project_018",
        contentId: "content_123",
        createdAt: "2026-08-12T08:29:00Z",
    },
    {
        id: "activity_024",
        type: "video_generated",
        title: "Video generated",
        description: 'Video successfully generated for "The Future of Robotics"',
        projectId: "project_009",
        contentId: "content_124",
        createdAt: "2026-08-12T08:03:00Z",
    },
    {
        id: "activity_025",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Space Facts Daily"',
        projectId: "project_004",
        contentId: "content_125",
        createdAt: "2026-08-12T07:41:00Z",
    },
    {
        id: "activity_026",
        type: "content_published",
        title: "Content published",
        description: '"The Science Behind Sleep" was published successfully',
        projectId: "project_010",
        contentId: "content_126",
        createdAt: "2026-08-12T07:15:00Z",
    },
    {
        id: "activity_027",
        type: "seo_metadata_generated",
        title: "SEO metadata generated",
        description: 'SEO suggestions ready for "Travel Stories"',
        projectId: "project_019",
        contentId: "content_127",
        createdAt: "2026-08-12T06:52:00Z",
    },
    {
        id: "activity_028",
        type: "thumbnail_generated",
        title: "Thumbnail generated",
        description: 'AI generated a thumbnail for "Extreme Weather Explained"',
        projectId: "project_020",
        contentId: "content_128",
        createdAt: "2026-08-12T06:28:00Z",
    },
    {
        id: "activity_029",
        type: "script_generated",
        title: "Script generated",
        description: 'AI generated a script for "Amazing Ocean Facts"',
        projectId: "project_011",
        contentId: "content_129",
        createdAt: "2026-08-12T06:04:00Z",
    },
    {
        id: "activity_030",
        type: "video_generated",
        title: "Video generated",
        description: 'Video successfully generated for "Artificial Intelligence 101"',
        projectId: "project_001",
        contentId: "content_130",
        createdAt: "2026-08-12T05:39:00Z",
    },
]