export const mockPendingReviews = [
    {
        id: "approval_001",
        contentId: "content_201",
        projectId: "project_005",
        title: "5 Amazing Facts About Space",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/space-facts.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 32,
        },
        createdAt: "2026-08-12T16:20:00Z",
    },
    {
        id: "approval_002",
        contentId: "content_202",
        projectId: "project_003",
        title: "The Science Behind Black Holes",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/black-holes.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 45,
        },
        createdAt: "2026-08-12T15:42:00Z",
    },
    {
        id: "approval_003",
        contentId: "content_203",
        projectId: "project_002",
        title: "10 Weird Animal Facts",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/animal-facts.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 38,
        },
        createdAt: "2026-08-12T14:58:00Z",
    },
    {
        id: "approval_004",
        contentId: "content_204",
        projectId: "project_007",
        title: "How Artificial Intelligence Works",
        status: "rejected",
        thumbnailUrl: "https://example.com/thumbnails/ai-explained.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 52,
        },
        createdAt: "2026-08-12T14:16:00Z",
    },
    {
        id: "approval_005",
        contentId: "content_205",
        projectId: "project_001",
        title: "The History of the Internet",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/internet-history.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 41,
        },
        createdAt: "2026-08-12T13:37:00Z",
    },
    {
        id: "approval_006",
        contentId: "content_206",
        projectId: "project_009",
        title: "7 Facts You Didn't Know About Mars",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/mars-facts.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 36,
        },
        createdAt: "2026-08-12T12:54:00Z",
    },
    {
        id: "approval_007",
        contentId: "content_207",
        projectId: "project_004",
        title: "Ancient Civilizations Explained",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/ancient-civilizations.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 58,
        },
        createdAt: "2026-08-12T12:11:00Z",
    },
    {
        id: "approval_008",
        contentId: "content_208",
        projectId: "project_006",
        title: "Why Do We Dream?",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/dreams.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 29,
        },
        createdAt: "2026-08-12T11:35:00Z",
    },
    {
        id: "approval_009",
        contentId: "content_209",
        projectId: "project_010",
        title: "The Future of Robotics",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/robotics.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 47,
        },
        createdAt: "2026-08-12T10:52:00Z",
    },
    {
        id: "approval_010",
        contentId: "content_210",
        projectId: "project_008",
        title: "10 Incredible Ocean Discoveries",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/ocean-discoveries.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 34,
        },
        createdAt: "2026-08-12T10:14:00Z",
    },
    {
        id: "approval_011",
        contentId: "content_211",
        projectId: "project_011",
        title: "The Human Brain in 60 Seconds",
        status: "rejected",
        thumbnailUrl: "https://example.com/thumbnails/human-brain.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 60,
        },
        createdAt: "2026-08-12T09:47:00Z",
    },
    {
        id: "approval_012",
        contentId: "content_212",
        projectId: "project_012",
        title: "5 Inventions That Changed the World",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/world-inventions.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 44,
        },
        createdAt: "2026-08-12T09:18:00Z",
    },
    {
        id: "approval_013",
        contentId: "content_213",
        projectId: "project_013",
        title: "How Volcanoes Really Work",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/volcanoes.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 39,
        },
        createdAt: "2026-08-12T08:51:00Z",
    },
    {
        id: "approval_014",
        contentId: "content_214",
        projectId: "project_014",
        title: "The Deepest Places on Earth",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/deepest-places.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 49,
        },
        createdAt: "2026-08-12T08:23:00Z",
    },
    {
        id: "approval_015",
        contentId: "content_215",
        projectId: "project_015",
        title: "Why Is the Sky Blue?",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/sky-blue.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 27,
        },
        createdAt: "2026-08-12T07:56:00Z",
    },
    {
        id: "approval_016",
        contentId: "content_216",
        projectId: "project_016",
        title: "The Mystery of the Bermuda Triangle",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/bermuda-triangle.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 43,
        },
        createdAt: "2026-08-11T18:42:00Z",
    },
    {
        id: "approval_017",
        contentId: "content_217",
        projectId: "project_017",
        title: "How Planes Stay in the Air",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/planes.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 35,
        },
        createdAt: "2026-08-11T17:29:00Z",
    },
    {
        id: "approval_018",
        contentId: "content_218",
        projectId: "project_018",
        title: "The Secrets of the Amazon Rainforest",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/amazon.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 51,
        },
        createdAt: "2026-08-11T16:18:00Z",
    },
    {
        id: "approval_019",
        contentId: "content_219",
        projectId: "project_019",
        title: "What Happens Inside a Tornado?",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/tornado.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 40,
        },
        createdAt: "2026-08-11T15:07:00Z",
    },
    {
        id: "approval_020",
        contentId: "content_220",
        projectId: "project_020",
        title: "The World's Most Mysterious Places",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/mysterious-places.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 55,
        },
        createdAt: "2026-08-11T14:26:00Z",
    },
    {
        id: "approval_021",
        contentId: "content_221",
        projectId: "project_003",
        title: "Quantum Physics Made Simple",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/quantum-physics.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 48,
        },
        createdAt: "2026-08-11T13:41:00Z",
    },
    {
        id: "approval_022",
        contentId: "content_222",
        projectId: "project_005",
        title: "Amazing Facts About the Moon",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/moon-facts.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 31,
        },
        createdAt: "2026-08-11T12:35:00Z",
    },
    {
        id: "approval_023",
        contentId: "content_223",
        projectId: "project_007",
        title: "How Social Media Algorithms Work",
        status: "rejected",
        thumbnailUrl: "https://example.com/thumbnails/social-algorithms.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 53,
        },
        createdAt: "2026-08-11T11:22:00Z",
    },
    {
        id: "approval_024",
        contentId: "content_224",
        projectId: "project_009",
        title: "The Fastest Animals on Earth",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/fastest-animals.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 37,
        },
        createdAt: "2026-08-11T10:16:00Z",
    },
    {
        id: "approval_025",
        contentId: "content_225",
        projectId: "project_010",
        title: "The Science of Happiness",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/happiness.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 46,
        },
        createdAt: "2026-08-11T09:34:00Z",
    },
    {
        id: "approval_026",
        contentId: "content_226",
        projectId: "project_011",
        title: "What If Earth Stopped Spinning?",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/earth-spinning.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 42,
        },
        createdAt: "2026-08-10T18:47:00Z",
    },
    {
        id: "approval_027",
        contentId: "content_227",
        projectId: "project_012",
        title: "The World's Greatest Engineering Marvels",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/engineering.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 57,
        },
        createdAt: "2026-08-10T16:32:00Z",
    },
    {
        id: "approval_028",
        contentId: "content_228",
        projectId: "project_014",
        title: "How GPS Knows Where You Are",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/gps.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 33,
        },
        createdAt: "2026-08-10T14:19:00Z",
    },
    {
        id: "approval_029",
        contentId: "content_229",
        projectId: "project_016",
        title: "The Strangest Weather on Earth",
        status: "approved",
        thumbnailUrl: "https://example.com/thumbnails/strange-weather.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1080x1920",
            durationSeconds: 50,
        },
        createdAt: "2026-08-10T11:43:00Z",
    },
    {
        id: "approval_030",
        contentId: "content_230",
        projectId: "project_018",
        title: "The Future of Space Exploration",
        status: "pending",
        thumbnailUrl: "https://example.com/thumbnails/space-exploration.jpg",
        metadata: {
            source: "ai_generated",
            resolution: "1920x1080",
            durationSeconds: 59,
        },
        createdAt: "2026-08-10T08:27:00Z",
    },
]
